### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by sunzhaoyang** [Osmose/advanced-open-file#117] opened 2016-05-21 13:08 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0-beta3
**System**: Mac OS X 10.11.5
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.16.2

### Stack Trace

Failed to activate the advanced-open-file package

```
At Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/node_modules/fbjs/lib/invariant.js:34:15)
    at Object.ReactOwner.addComponentAsRefTo (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactOwner.js:67:373)
    at attachRef (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactRef.js:23:16)
    at Object.ReactRef.attachRefs (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactRef.js:42:5)
    at ReactDOMComponent.attachRefs (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactReconciler.js:24:12)
    at CallbackQueue._assign.notifyAll (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/CallbackQueue.js:66:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactReconcileTransaction.js:79:26)
    at ReactReconcileTransaction.Mixin.closeAll (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/Transaction.js:202:25)
    at ReactReconcileTransaction.Mixin.perform (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/Transaction.js:149:16)
    at batchedMountComponentIntoNode (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactMount.js:123:15)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactUpdates.js:98:20)
    at Object.ReactMount._renderNewRootComponent (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactMount.js:286:18)
    at Object.ReactMount._renderSubtreeIntoContainer (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactMount.js:365:32)
    at Object.ReactMount.render (/Users/Sun/.atom/packages/advanced-open-file/node_modules/react/lib/ReactMount.js:386:23)
    at new AdvancedOpenFileView (/Users/Sun/.atom/packages/advanced-open-file/lib/view.js:23:33)
    at new AdvancedOpenFileController (/Users/Sun/.atom/packages/advanced-open-file/lib/controller.js:23:21)
    at Object.activate (/Users/Sun/.atom/packages/advanced-open-file/lib/advanced-open-file.js:11:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused.vim-mode.normal-mode.hyperclick)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-pylint",
      "project-ring",
      "python-jedi",
      "linter-bootlint",
      "atom-htmltidy",
      "keybinding-resolver",
      "python-yapf",
      "linter-pyflakes",
      "activate-power-mode",
      "git-projects"
    ],
    "ignoredNames": [
      "*.pyc",
      ".gitignore"
    ],
    "packagesWithKeymapsDisabled": [
      "advanced-open-file"
    ],
    "projectHome": "/Users/Sun/Projects/three-color",
    "themes": [
      "genesis-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.9
advanced-open-file, v0.16.2
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
autocomplete-python, v1.7.3
color-tabs-regex, v0.2.3
environment, v1.2.0
file-icons, v1.7.12
file-type-icons, v1.3.0
formatter, v2.12.3
genesis-ui, v0.5.0
highlight-selected, v0.11.2
hyperclick, v0.0.36
jsformat, v0.9.3
language-python, v0.44.0
linter, v1.11.4
linter-flake8, v1.13.0
merge-conflicts, v1.4.2
pigments, v0.26.3
project-manager, v2.9.7
python-autopep8, v0.1.3
python-debugger, v0.1.0
python-indent, v0.4.3
python-iresolve, v0.0.3
python-mrigor, v2.1.3
python-tools, v0.6.7
regex-railroad-diagram, v0.16.0
symbols-tree-view, v0.12.0
template-insert, v2.0.3
tree-view-git-status, v0.2.3
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by Osmose** [comment] 2016-05-21 15:59
Thanks for the report!

This is a duplicate of #116, closing it in favor of that issue.

**Closed by Osmose** 2016-05-21 15:59 UTC
