### ISSUE TITLE
UI elements shifted to inconvinient position

### ISSUE THREAD

**Issue by tepf** [Osmose/advanced-open-file#92] opened 2016-02-10 11:17 UTC
This was not always the case. About 5 updates ago it was still showing correctly but now the first folder interferes with the input box.

![fileopen](https://cloud.githubusercontent.com/assets/14161807/12945639/2dd65e1a-cfef-11e5-8a8c-1a07024a9bdf.png)

Is it also possible to have a little more top margin at "Enter the path for the file to open or create"?

I managed to do that just by adding change those 2 CSS classes. But apparently you haven't noticed it so it might break your UI.

    .advanced-open-file {
        display: flex;
        flex-direction: column;
        overflow: hidden;
        z-index: 100;
        margin-top: 5px; // added this

        ...
        ... other css code
        ...

        .list-group {
            overflow: auto;
            flex: 2;
            position: relative;
            margin-top: 16px; // added this
        }

        ...
        ... more css
        ...

    }

**Comment by Osmose** [comment] 2016-02-10 17:00
Thanks for the report!

Can you share which theme you're using? It'd help me reproduce and test these changes.

**Comment by tepf** [comment] 2016-02-10 18:09
UI Theme is Atom Material and Syntax Theme is Gruvbox

**Comment by jamby** [comment] 2016-02-15 16:06
Yeah I, too, am using Atom Material theme and this is happening to me. Looks like the "text area" is lower than it should be too. It's too far below the "+ Enter the path ...".

**Comment by Osmose** [comment] 2016-02-22 06:52
I just tried to replicate this and failed; it looks fine to me (in terms of the textarea, the padding at the top is still awkward and I'm trying to figure out if there's a theme variable I can take advantage of for that). I'm on OSX El Capitan, what platforms are ya'll on?

**Comment by jamby** [comment] 2016-02-22 15:31
I'm also on OS X El Capitan.

<img width="521" alt="screen shot 2016-02-22 at 10 29 47 am" src="https://cloud.githubusercontent.com/assets/250728/13222744/64440be6-d94f-11e5-89d2-cb79ffebefd0.png">

This is how mine looks, without the styling.

**Comment by jamby** [comment] 2016-02-22 21:20
@Osmose This actually seems to be fixed in the latest update to the Material Theme.

**Comment by Osmose** [comment] 2016-02-29 03:21
> @Osmose This actually seems to be fixed in the latest update to the Material Theme.

Yeah. I wanted to see about fixing the weird spacing at the top but ran into issues because the theme now has specific fixes for this package that are adding some padding that was interfering. I think I'll just call this fixed, I'm fine with themes having their own fixes; working for every theme is too difficult for me otherwise.

Thanks again!

**Closed by Osmose** 2016-02-29 03:21 UTC
