### ISSUE TITLE
Newly created file does not show up in CTRL + P menu

### ISSUE THREAD

**Issue by bluenote10** [Osmose/advanced-open-file#55] opened 2015-10-04 12:07 UTC
When I create a file using advanced open file, I cannot switch to this file using the <kbd>CTRL</kbd>+<kbd>P</kbd> menu -- the newly created file simply does not appear.

I'm completely new to Atom, so apologies if this is not actually an issue of this package.

**Comment by Osmose** [comment] 2015-10-04 16:33
This is a duplicate of #25, which came to the conclusion that you suspected: this is an issue with the fuzzy finder, not advanced-open-file. No worries though, thanks for the report!

Note also that unless you have the "Create files instantly" checkbox checked, files aren't actually created and available for indexing until you save them. That might also be part of the cause.

Hope that helps!

**Closed by Osmose** 2015-10-04 16:33 UTC

**Comment by bluenote10** [comment] 2015-10-04 18:07
Yes, thanks a lot for the clarification.

Following the link to the fuzzy-finder-bug I could also find a work around: To make the file appear, I now save the new file and do a window:reload (<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>R</kbd>).
