### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open 'tools.txt'

### ISSUE THREAD

**Issue by KCreate** [Osmose/advanced-open-file#65] opened 2015-11-09 02:07 UTC
[Enter steps to reproduce below:]

1. Tried to create a new file

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.12.0

### Stack Trace

Uncaught Error: EACCES: permission denied, open 'tools.txt'

```
At fs.js:549

Error: EACCES: permission denied, open 'tools.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at openThenF (/Users/leonardschuetz/.atom/packages/advanced-open-file/node_modules/touch/touch.js:80:40)
    at touch_ (/Users/leonardschuetz/.atom/packages/advanced-open-file/node_modules/touch/touch.js:73:10)
    at optionsRef (/Users/leonardschuetz/.atom/packages/advanced-open-file/node_modules/touch/touch.js:45:28)
    at touch (/Users/leonardschuetz/.atom/packages/advanced-open-file/node_modules/touch/touch.js:69:10)
    at Function.touch.touchSync.touch.sync (/Users/leonardschuetz/.atom/packages/advanced-open-file/node_modules/touch/touch.js:6:10)
    at Path.createFile (/Users/leonardschuetz/.atom/packages/advanced-open-file/lib/models.js:107:15)
    at AdvancedOpenFileController.openPath (/Users/leonardschuetz/.atom/packages/advanced-open-file/lib/controller.js:107:22)
```

### Commands

```
     -0:04.1.0 advanced-open-file:toggle (atom-pane.pane.active)
     -0:02.5.0 core:backspace (atom-text-editor.path-input.editor.mini.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.path-input.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "metrics"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-vivid-syntax"
    ],
    "projectHome": "/www/sites/leonardschuetz/wwwroot"
  },
  "advanced-open-file": {
    "createFileInstantly": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.12.0
atom-material-ui, v0.7.1
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
autocomplete-python, v0.10.3
bezier-curve-editor, v0.7.2
editor-stats, v0.17.0
emmet, v2.3.14
file-icons, v1.6.11
jshint, v1.8.3
json-colorer, v0.3.0
linter, v1.10.0
one-dark-vivid-syntax, v1.1.1
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by Osmose** [comment] 2015-11-10 06:32
Thanks for the report!

I think this is a duplicate of #67, so I'm going to close this since that has been fixed. I mentioned in that issue that a release should be going out sometime tonight with a fix, feel free to reopen this if you're still seeing the issue after upgrading.

**Closed by Osmose** 2015-11-10 06:32 UTC
